version: '3'


services:
   zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./zk-single-kafka-single/zoo1/data:/data
      - ./zk-single-kafka-single/zoo1/datalog:/datalog
    networks:
      - somenetwork

   kafka1:
    image: confluentinc/cp-kafka:5.3.0
    hostname: kafka1
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
    networks:
      - somenetwork

   es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - somenetwork
   dynamo:
    image: "dwmkerr/dynamodb"
    volumes:
      - ./.data/dynamodb:/dynamodb_local_db
    ports:
      - "8000:8000"
    networks:
      - somenetwork
   outng-orchestrator-app:
    container_name: outng-orchestrator-app
    image: outng/outng-orchestrator-image:1.0.0-SNAPSHOT
    ports:
      - "8086:8086"
    links:
      - dynamo
    networks:
      - somenetwork

   outng-async-app:
    container_name: outng-async-app
    image: outng/outng-async-image:1.0.0-SNAPSHOT
    ports:
      - "8088:8088"
    links:
      - dynamo
    networks:
      - somenetwork

   outng-chat-app:
    container_name: outng-chat-app
    image: outng/outng-chat-image:1.0.0-SNAPSHOT
    ports:
      - "8087:8087"


networks:
  somenetwork:
    external: true
