package com.dapp.outng.common.models.user;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@JsonInclude(Include.NON_NULL)
@DynamoDBTable(tableName = "User_Test")
public class OutngUser {

	@DynamoDBHashKey(attributeName = "userId")
	@DynamoDBAutoGeneratedKey
	private String userId;
	@DynamoDBAttribute(attributeName = "name")
	private String name;
	@DynamoDBAttribute(attributeName = "birthDate")
	private String birthDate;
	private String age;
	@DynamoDBAttribute(attributeName = "email")
	private String email;
	@DynamoDBAttribute(attributeName = "location")
	private Location location;
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "partnerUserId")
	private String partnerUserId;
	@DynamoDBAttribute(attributeName = "partnerUserType")
	private String partnerUserType;
	@DynamoDBAttribute(attributeName = "preference")
	private UserPreference preference;
	@DynamoDBAttribute(attributeName = "userDetail")
	private UserDetail userDetail;
	@DynamoDBAttribute(attributeName = "photos")
	private List<String> photos;

	public OutngUser() {

	}
	
}
