package com.dapp.outng.common.models.user;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="User_Test")
public class OutngUser {
	
	@DynamoDBHashKey(attributeName = "userId")
    @DynamoDBAutoGeneratedKey
	private String userId;
	@DynamoDBAttribute(attributeName = "name")
	private String name;
	private String birthDate;
	private Location location; 
	@DynamoDBIndexHashKey(globalSecondaryIndexName="clientUserId")
	private String clientUserId;
	private String clientUserType;
	private String gender;
	private String lookingFor;
	private List<String> situation; 
	private List<String> interests;
	private UserPreference preference;
	private UserDetail userDetail;
	
	
	

}
