//package com.dapp.outng.profile.models;
//
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
//
//@DynamoDBTable(tableName = "Profile")
//public class Profile {
//
//	private String id;
//	private String name;
//
//	public Profile(String id, String name) {
//		super();
//		this.id = id;
//		this.name = name;
//	}
//
//	@DynamoDBHashKey
//	@DynamoDBAutoGeneratedKey
//	public String getId() {
//		return id;
//	}
//
//	public void setId(String id) {
//		this.id = id;
//	}
//
//	@DynamoDBAttribute
//	public String getName() {
//		return name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//}
